-- ============================================================================
-- SportDay — heat / final split for the short sprints (60/100/200/400).
--
-- Run once against an existing database, BEFORE starting the backend:
--
--   docker exec -i sportday-mysql mysql -usportday -psportday123 -D sportday \
--     < backend/db/migration/final-stage-migration.sql
--
-- A brand new database needs none of this: ddl-auto=update creates both columns
-- and the (user_id, event_id, stage) key from the entity annotations.
--
-- Why it cannot be left to ddl-auto: Hibernate's schema *update* adds the new
-- `stage` columns happily, but it never drops the old unique key on
-- event_results. That key is (user_id, event_id), which would stop an athlete
-- from holding both a heat and a final mark — exactly what this feature needs.
--
-- The script is idempotent: running it twice is harmless.
-- ============================================================================

-- 1. Stage columns. Nullable, so pre-existing rows read as NULL and are then
--    backfilled to HEAT; the application writes HEAT explicitly for new rows.
SET @sql := IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'event_groups' AND COLUMN_NAME = 'stage') > 0,
    'SELECT 1',
    'ALTER TABLE event_groups ADD COLUMN stage ENUM(''FINAL'',''HEAT'') NULL');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'event_results' AND COLUMN_NAME = 'stage') > 0,
    'SELECT 1',
    'ALTER TABLE event_results ADD COLUMN stage ENUM(''FINAL'',''HEAT'') NULL');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- 2. Everything that existed before the split is a heat.
UPDATE event_groups  SET stage = 'HEAT' WHERE stage IS NULL;
UPDATE event_results SET stage = 'HEAT' WHERE stage IS NULL;

-- 3. Replace the single-stage unique key on event_results with a per-stage one.
--    The old key's name is generated by Hibernate, so it is looked up rather
--    than hard-coded.
--
--    ORDER MATTERS. The foreign key on user_id is currently satisfied by the old
--    unique key, and MySQL refuses to drop the only index that backs a foreign
--    key ("Cannot drop index ...: needed in a foreign key constraint"). The new
--    key starts with user_id, so creating it FIRST gives the foreign key
--    somewhere else to live and the old key can then be dropped.
SET @sql := IF(
    (SELECT COUNT(*) FROM information_schema.STATISTICS
     WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'event_results'
       AND INDEX_NAME = 'uk_result_user_event_stage') > 0,
    'SELECT 1',
    'ALTER TABLE event_results ADD UNIQUE KEY uk_result_user_event_stage (user_id, event_id, stage)');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @old := (
    SELECT INDEX_NAME FROM information_schema.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'event_results'
      AND NON_UNIQUE = 0
      AND INDEX_NAME <> 'PRIMARY'
      AND INDEX_NAME <> 'uk_result_user_event_stage'
    GROUP BY INDEX_NAME
    HAVING GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) = 'user_id,event_id'
    LIMIT 1);
SET @sql := IF(@old IS NULL, 'SELECT 1',
               CONCAT('ALTER TABLE event_results DROP INDEX `', @old, '`'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- 4. The final is group number 0 (heats start at 1), so the existing
--    (event_id, group_number) key already accommodates it and needs no change.
